name: Build with makelove

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies and add LOVE2D PPA
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:bartbes/love-stable
        sudo apt update
        sudo apt install -y python3-pip python3-venv python3-setuptools pipx love

    - name: Upgrade pip and setuptools before pipx install
      run: |
        python3 -m pip install --upgrade pip setuptools

    - name: Ensure pipx path and install makelove
      run: |
        python3 -m pipx ensurepath
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        pipx install makelove

    - name: Inject setuptools into makelove pipx environment
      run: |
        pipx inject makelove setuptools

    - name: Run makelove build
      run: |
        makelove

    - name: Upload build artifacts (build directory)
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/

    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v4
      with:
        name: appimage
        path: appimage/squashfs-root/

    - name: Upload lovejs artifact
      uses: actions/upload-artifact@v4
      with:
        name: lovejs
        path: lovejs/CosmicCities-lovejs.zip

    - name: Upload macos artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: macos/CosmicCities-macos.zip

    - name: Upload win32 artifact
      uses: actions/upload-artifact@v4
      with:
        name: win32
        path: win32/CosmicCities-win32.zip

    - name: Upload win64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: win64
        path: win64/CosmicCities-win64.zip
