name: Build LOVE2D Game

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows 64-bit
            arch: win64
            os: windows-latest
            url: https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
          - name: Windows 32-bit
            arch: win32
            os: windows-latest
            url: https://github.com/love2d/love/releases/download/11.5/love-11.5-win32.zip

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Create game.love
        shell: pwsh
        run: |
          Compress-Archive -Path * -DestinationPath game.zip -Force
          Rename-Item -Path game.zip -NewName game.love

      - name: Download LOVE2D Runtime
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "${{ matrix.config.url }}" -OutFile love.zip
          Expand-Archive -Path love.zip -DestinationPath love

      - name: Download rcedit
        shell: pwsh
        run: |
          mkdir tools
          Invoke-WebRequest -Uri https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe -OutFile tools\rcedit.exe
          
      - name: Build Executable - concat love.exe and game.love
        shell: pwsh
        run: |
            $loveRuntimeFolder = Get-ChildItem -Path "${{ github.workspace }}\love" -Directory | Where-Object { $_.Name -like "love-11.5-*" } | Select-Object -First 1
            if (-not $loveRuntimeFolder) {
            Write-Error "LOVE2D runtime folder not found."
            exit 1
            }
            $loveRuntimePath = $loveRuntimeFolder.FullName
            Set-Location $loveRuntimePath
            cmd /c "copy /b love.exe+game.love CosmicCities.exe"
    
            $outputExePath = Join-Path $loveRuntimePath "CosmicCities.exe"
            if (-not (Test-Path $outputExePath)) {
            Write-Error "Failed to create CosmicCities.exe at $outputExePath"
            exit 1
            }
            Write-Host "Successfully created CosmicCities.exe at $outputExePath"

      - name: Copy game.love to runtime folder
        shell: pwsh
        run: |
            $loveRuntimeFolder = Get-ChildItem -Path "${{ github.workspace }}\love" -Directory | Where-Object { $_.Name -like "love-11.5-*" } | Select-Object -First 1
            if (-not $loveRuntimeFolder) {
            Write-Error "LOVE2D runtime folder not found."
            exit 1
            }
            $loveRuntimePath = $loveRuntimeFolder.FullName
            $gameLovePath = Join-Path "${{ github.workspace }}" "game.love"
            Copy-Item -Path $gameLovePath -Destination $loveRuntimePath -Force


      - name: Set Icon and Cleanup
        shell: pwsh
        run: |
          $loveRuntimeFolder = Get-ChildItem -Path "${{ github.workspace }}\love" -Directory | Where-Object { $_.Name -like "love-11.5-*" } | Select-Object -First 1
          if (-not $loveRuntimeFolder) {
              Write-Error "LOVE2D runtime folder not found for icon setting."
              exit 1
          }
          $loveRuntimePath = $loveRuntimeFolder.FullName
          $exePath = Join-Path $loveRuntimePath "CosmicCities.exe"
          $iconPath = Join-Path "${{ github.workspace }}" "icons\icon64.ico"

          & "${{ github.workspace }}\tools\rcedit.exe" $exePath --set-icon $iconPath

          Set-Location $loveRuntimePath
          Remove-Item -Path love.exe, game.love, readme.txt, changes.txt, game.ico, love.ico, lovec.exe -ErrorAction SilentlyContinue

      - name: Upload folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CosmicCities-${{ matrix.config.arch }}
          path: love/love-11.5-*
