name: Compile LÖVE Project

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        target:
          - label: Win64
            bit: x64
            runner: windows-latest
            runtime: https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
          - label: Win32
            bit: x86
            runner: windows-latest
            runtime: https://github.com/love2d/love/releases/download/11.5/love-11.5-win32.zip

    name: Build ${{ matrix.target.label }}
    runs-on: ${{ matrix.target.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Bundle Game Files
        shell: pwsh
        run: |
          Compress-Archive -Path * -DestinationPath payload.zip -Force
          Rename-Item payload.zip packed.love

      - name: Fetch Engine Runtime
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "${{ matrix.target.runtime }}" -OutFile runtime.zip
          Expand-Archive runtime.zip -DestinationPath engine

      - name: Acquire RCEdit Utility
        shell: pwsh
        run: |
          New-Item -Path bin -ItemType Directory -Force
          Invoke-WebRequest -Uri https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe -OutFile bin\rcedit.exe

      - name: Create Executable Binary
        shell: pwsh
        run: |
          $engineDir = Get-ChildItem engine -Directory | Where-Object { $_.Name -like "love-11.5-*" } | Select-Object -First 1
          if (-not $engineDir) {
            throw "Missing LOVE2D runtime directory."
          }
          $dir = $engineDir.FullName
          $loveExePath = Join-Path $dir "love.exe"
          $packedLovePath = Join-Path $PWD "packed.love"
          $outputExePath = Join-Path $dir "CosmicCities.exe"

          $exeBytes = [System.IO.File]::ReadAllBytes($loveExePath)
          $loveBytes = [System.IO.File]::ReadAllBytes($packedLovePath)
          $combined = New-Object byte[] ($exeBytes.Length + $loveBytes.Length)
          [System.Buffer]::BlockCopy($exeBytes, 0, $combined, 0, $exeBytes.Length)
          [System.Buffer]::BlockCopy($loveBytes, 0, $combined, $exeBytes.Length, $loveBytes.Length)
          [System.IO.File]::WriteAllBytes($outputExePath, $combined)

          if (-not (Test-Path $outputExePath)) {
            throw "Build failed: CosmicCities.exe not created."
          }

      - name: Place Game Source File
        shell: pwsh
        run: |
          $engineDir = Get-ChildItem engine -Directory | Where-Object { $_.Name -like "love-11.5-*" } | Select-Object -First 1
          if (-not $engineDir) {
            throw "Runtime folder not found."
          }
          Copy-Item -Path .\packed.love -Destination $engineDir.FullName -Force

      - name: Apply Icon and Clean Extras
        shell: pwsh
        run: |
          $engineDir = Get-ChildItem engine -Directory | Where-Object { $_.Name -like "love-11.5-*" } | Select-Object -First 1
          if (-not $engineDir) {
            throw "Directory missing for icon assignment."
          }
          $exe = Join-Path $engineDir.FullName "CosmicCities.exe"
          $ico = Join-Path $PWD "icons\icon64.ico"
          & ".\bin\rcedit.exe" $exe --set-icon $ico
          Set-Location $engineDir.FullName
          Remove-Item love.exe, packed.love, readme.txt, changes.txt, game.ico, love.ico, lovec.exe -ErrorAction Ignore

      - name: Archive Final Output
        uses: actions/upload-artifact@v4
        with:
          name: CosmicCities-${{ matrix.target.bit }}
          path: engine/love-11.5-*
