name: Build LOVE2D Game

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows 64-bit
            arch: win64
            os: windows-latest
            url: https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip

          - name: Windows 32-bit
            arch: win32
            os: windows-latest
            url: https://github.com/love2d/love/releases/download/11.5/love-11.5-win32.zip

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Create game.love
        run: |
          powershell -Command "Compress-Archive -Path * -DestinationPath game.zip"
          Rename-Item -Path game.zip -NewName game.love

      - name: Download LOVE2D Runtime
        run: |
          curl -L -o love.zip "${{ matrix.config.url }}"
          powershell -Command "Expand-Archive -Path love.zip -DestinationPath love"

      - name: Download rcedit
        run: |
          mkdir tools
          curl -L -o tools/rcedit.exe https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe

      - name: Build Executable
        shell: pwsh
        run: |
          cd love
          $folder = Get-ChildItem -Directory | Where-Object { $_.Name -like "love-11.5-*" } | Select-Object -First 1
          cd $folder.FullName
          Copy-Item ..\..\game.love .
          if (-Not (Test-Path game.love)) { exit 1 }

          $loveExePath = (Resolve-Path love.exe).Path
          $gameLovePath = (Resolve-Path game.love).Path
          $outputExePath = Join-Path (Get-Location) "CosmicCities.exe"

          if (Test-Path $outputExePath) {
            Remove-Item $outputExePath
          }

          $bytesExe = [System.IO.File]::ReadAllBytes($loveExePath)
          $bytesLove = [System.IO.File]::ReadAllBytes($gameLovePath)
          $combinedBytes = New-Object byte[] ($bytesExe.Length + $bytesLove.Length)

          [System.Buffer]::BlockCopy($bytesExe, 0, $combinedBytes, 0, $bytesExe.Length)
          [System.Buffer]::BlockCopy($bytesLove, 0, $combinedBytes, $bytesExe.Length, $bytesLove.Length)

          [System.IO.File]::WriteAllBytes($outputExePath, $combinedBytes)

          $iconPath = "${{ github.workspace }}\icons\icon64.ico"
          & "${{ github.workspace }}\tools\rcedit.exe" $outputExePath --set-icon $iconPath

          Remove-Item love.exe, game.love, readme.txt, changes.txt, game.ico, love.ico, lovec.exe

      - name: Upload folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: CosmicCities-${{ matrix.config.arch }}
          path: love/love-11.5-*
